BoschTrafficRecognition/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csv/', include('csvFile.urls')),
    path('img/', include('imguploader.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csvFile/urls.py
from django.urls import path

from .views import show, upload_file, export_file,train_model

urlpatterns = [
    path('show/', show, name="show"),
    path('upload/', upload_file, name="upload_file"),
    path('export/', export_file, name="export_file"),
    path('train/',train_model,name="train_model"),
]

imguploader/urls.py
from django.urls import path
from .views import image_upload, ImageListView, ImageDetailView
from django.conf.urls.static import static
from django.conf import settings


app_name = 'imguploader'

urlpatterns = [
    path('', ImageListView.as_view(), name="image_list"),
    path('upload/', image_upload, name="imageup"),
    path('view/<slug:slug>/', ImageDetailView.as_view(), name="view_image"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imguploader/models.py
from django.db import models
import random
import os
from django.db.models.signals import pre_save, post_save
from django.db.models import Q

from .utils import unique_slug_generator


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    print(instance)
    new_filename = random.randint(1, 3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(
        new_filename=new_filename, ext=ext)
    return "images/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )


class ImageQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def search(self, query):
        lookups = (Q(slug__icontains=query)
                   )
        return self.filter(lookups).distinct()


# Query parameters decoder. Its splitted in manager
class ImageManager(models.Manager):
    def get_queryset(self):
        return ImageQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


class ImgUp(models.Model):
    # Slug for trversing between images usign custom url
    slug = models.SlugField(blank=True, unique=True)
    image = models.ImageField(
        upload_to=upload_image_path, null=True, blank=True)
    active = models.BooleanField(default=True)

    objects = ImageManager()  # Object of ImageManager

    def get_absolute_url(self):
        return "/img/view/{slug}/".format(slug=self.slug)

    def __str__(self):
        return self.slug

    def __unicode__(self):
        return self.slug


# its is a function thats is called by the pre_sav funtion automatically
# when a new image is uploaded
def image_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


# It gets executed automatically whenever new image is uploaded.
pre_save.connect(image_pre_save_receiver, sender=ImgUp)

imguploader/forms.py
from django import forms
from . import models

class UploadImage(forms.ModelForm):
    class Meta:
        model = models.ImgUp
        fields = ['image']

imguploader/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from . import forms
from django.http import Http404

from .models import ImgUp

import logging
logger = logging.getLogger(__name__)

# Create your views here.


def image_upload(request):
    if request.method == 'POST':
        form = forms.UploadImage(request.POST, request.FILES)
        try:
            img_file = request.FILES['image']
            if (img_file.name.endswith('.jpg')) or (img_file.name.endswith('.jpeg')) or (img_file.name.endswith('.png')):
                form.save()
                return render(request, 'imguploader/imgup.html', {'result':'success'})
        except: 
            return render(request,'imguploader/imgup.html',{'error':'No File selected'})    
    else:
       form = forms.UploadImage()
    return render(request, 'imguploader/imgup.html', {'form': form})


class ImageListView(ListView):
    template_name = "imguploader/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        t = ImgUp.objects.all()
        print(type(t))
        return ImgUp.objects.all()


class ImageDetailView(DetailView):
    queryset = ImgUp.objects.all()
    template_name = "imguploader/detail.html"

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = ImgUp.objects.get(slug=slug, active=True)
        except ImgUp.DoesNotExist:
            raise Http404("Not Found")
        except ImgUp.MultipleObjectsReturned:
            qs = ImgUp.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Uhmmm  ")
        return instance

imguploader/templates/imguploader/detail.html
{% extends "base.html" %}
{% block base_end %}
{% load static  %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}
{% block content %}

<div class='row'>
    <div class='col'>
        {% if object.image %}
        <img src='{{ object.image.url }}' class='img-fluid' style="height: 100vh; width: 100vh;" />
        {% endif %}
    </div>
</div>
{% endblock %}

imguploader/templates/imguploader/imgup.html
{% extends "base.html" %}
 {% block base_up %} 
 {% load static %}
    <link rel="stylesheet" href="{% static 'css/css1.css' %}">
  {% endblock %}
    {% block base_end %} 
     <title>Image Uploader</title>
     {% endblock %}
    {% block content %}
    <div class="formcsv">
        <div class="alert alert-info" style="margin-bottom: 0;text-align: center; background-color:#343a40; color:white;">
            Image should have extention .jpg, .jpeg or .png
        </div>
        <div class="jumbotron">
            <div class="form-header" style="text-align: center;">
                <h1>Upload Image</h1>
            </div>
            <div style="text-align: center;">
                {% if result %}
                <div class="alert alert-success" style="text-align: center;">
                    <strong>Succesfully uploaded the data</strong>
                </div>
                <p>
                    <a href="{% url 'imguploader:imageup' %}" class="btn btn-success btn-lg">Upload another Image</a>
                </p>
                {% elif error %}
                <div class="alert alert-danger" style="text-align: center;">
                    <strong>No File Selected</strong>
                </div>
                <p>
                    <a href="{% url 'imguploader:imageup' %}" class="btn btn-primary">Upload Again</a>
                </p>
                {% else %}
                <form class="site-form" action="{% url 'imguploader:imageup' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %} {{ form }}
                    <input type="submit" class="btn btn-primary" value="Upload">
                </form>
                <p style="text-align: center;">
                    <a href="{% url 'imguploader:image_list' %}" class="btn btn-success" style="margin: 20px;">See Gallery</a>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
     

{% endblock %}

imguploader/templates/imguploader/list.html
{% extends "base.html" %} 
{% block base_end %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<title>Gallery</title>
{% endblock %}

{% block content %}
   <h1 class="heading">Image Gallery</h1>
    <div class="gallery">
    {% for instance in object_list %}
        <div class="gallery-item">
            <img class="gallery-image" src="{{ instance.image.url }}">
            <div class="btn-middle">
                <a href="{{ instance.get_absolute_url }}" class="btn btn-primary" style="font-size: 150%;">View</a>
            </div>
        </div>
    {% endfor %}

    </div>
    <p style="text-align: end;">
        <a href="{% url 'imguploader:imageup' %}" class="btn btn-primary btn-lg" style="margin: 20px;">Upload Image</a>
    </p>
{% endblock %}